# uncompyle6 version 3.7.4
# Python bytecode 2.6 (62161)
# Decompiled from: Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
# Embedded file name: \\pldatafile01\data\misc\labeldesigner\LabelDesigner.py
# Compiled at: 2020-03-04 11:56:02
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s


class Ui_MainWindow(QtWidgets.QMainWindow):

    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8('MainWindow'))
        MainWindow.resize(1218, 891)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8('centralwidget'))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8('verticalLayout_4'))
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8('frame'))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setSpacing(0)
##        self.horizontalLayout_4.setMargin(0)
        # QHBoxLayout has no setMargin method in PyQt5?
        self.horizontalLayout_4.setObjectName(_fromUtf8('horizontalLayout_4'))
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8('groupBox_4'))
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName(_fromUtf8('verticalLayout_8'))
        self.headerList = QtWidgets.QTableWidget(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerList.sizePolicy().hasHeightForWidth())
        self.headerList.setSizePolicy(sizePolicy)
        self.headerList.setMinimumSize(QtCore.QSize(300, 0))
        self.headerList.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.headerList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.headerList.setObjectName(_fromUtf8('headerList'))
        self.headerList.setColumnCount(0)
        self.headerList.setRowCount(0)
        self.headerList.verticalHeader().setVisible(False)
        self.verticalLayout_8.addWidget(self.headerList)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName(_fromUtf8('groupBox_3'))
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName(_fromUtf8('horizontalLayout_7'))
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8('verticalLayout_10'))
        self.layoutList = QtWidgets.QListWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutList.sizePolicy().hasHeightForWidth())
        self.layoutList.setSizePolicy(sizePolicy)
        self.layoutList.setMinimumSize(QtCore.QSize(500, 250))
        self.layoutList.setObjectName(_fromUtf8('layoutList'))
        self.verticalLayout_10.addWidget(self.layoutList)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8('horizontalLayout_8'))
        self.filterLabel = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterLabel.sizePolicy().hasHeightForWidth())
        self.filterLabel.setSizePolicy(sizePolicy)
        self.filterLabel.setObjectName(_fromUtf8('filterLabel'))
        self.horizontalLayout_8.addWidget(self.filterLabel)
        self.filterEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.filterEdit.setObjectName(_fromUtf8('filterEdit'))
        self.horizontalLayout_8.addWidget(self.filterEdit)
        self.dateSort = QtWidgets.QCheckBox(self.groupBox_3)
        self.dateSort.setObjectName(_fromUtf8('dateSort'))
        self.horizontalLayout_8.addWidget(self.dateSort)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7.addLayout(self.verticalLayout_10)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8('verticalLayout_6'))
        self.loadLayout = QtWidgets.QPushButton(self.groupBox_3)
        self.loadLayout.setObjectName(_fromUtf8('loadLayout'))
        self.verticalLayout_6.addWidget(self.loadLayout)
        self.saveLayout = QtWidgets.QPushButton(self.groupBox_3)
        self.saveLayout.setObjectName(_fromUtf8('saveLayout'))
        self.verticalLayout_6.addWidget(self.saveLayout)
        self.renameLayout = QtWidgets.QPushButton(self.groupBox_3)
        self.renameLayout.setObjectName(_fromUtf8('renameLayout'))
        self.verticalLayout_6.addWidget(self.renameLayout)
        self.refreshLayoutList = QtWidgets.QPushButton(self.groupBox_3)
        self.refreshLayoutList.setObjectName(_fromUtf8('refreshLayoutList'))
        self.verticalLayout_6.addWidget(self.refreshLayoutList)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.removeLayout = QtWidgets.QPushButton(self.groupBox_3)
        self.removeLayout.setObjectName(_fromUtf8('removeLayout'))
        self.verticalLayout_6.addWidget(self.removeLayout)
        self.clearFilter = QtWidgets.QPushButton(self.groupBox_3)
        self.clearFilter.setObjectName(_fromUtf8('clearFilter'))
        self.verticalLayout_6.addWidget(self.clearFilter)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8('groupBox_2'))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName(_fromUtf8('verticalLayout_5'))
        self.createPdfBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.createPdfBtn.setObjectName(_fromUtf8('createPdfBtn'))
        self.verticalLayout_5.addWidget(self.createPdfBtn)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8('horizontalLayout_10'))
        self.printButton = QtWidgets.QPushButton(self.groupBox_2)
        self.printButton.setObjectName(_fromUtf8('printButton'))
        self.horizontalLayout_10.addWidget(self.printButton)
        self.pageSetup = QtWidgets.QPushButton(self.groupBox_2)
        self.pageSetup.setObjectName(_fromUtf8('pageSetup'))
        self.horizontalLayout_10.addWidget(self.pageSetup)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8('horizontalLayout_13'))
        self.averyRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.averyRadio.setChecked(False)
        self.averyRadio.setAutoRepeat(False)
        self.averyRadio.setObjectName(_fromUtf8('averyRadio'))
        self.printerSelectGroup = QtWidgets.QButtonGroup(MainWindow)
        self.printerSelectGroup.setObjectName(_fromUtf8('printerSelectGroup'))
        self.printerSelectGroup.addButton(self.averyRadio)
        self.horizontalLayout_13.addWidget(self.averyRadio)
        self.zebraRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.zebraRadio.setChecked(True)
        self.zebraRadio.setObjectName(_fromUtf8('zebraRadio'))
        self.printerSelectGroup.addButton(self.zebraRadio)
        self.horizontalLayout_13.addWidget(self.zebraRadio)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8('line'))
        self.verticalLayout_5.addWidget(self.line)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8('horizontalLayout_6'))
        self.useSubset = QtWidgets.QCheckBox(self.groupBox_2)
        self.useSubset.setObjectName(_fromUtf8('useSubset'))
        self.horizontalLayout_6.addWidget(self.useSubset)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8('label_4'))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.subsetBottom = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subsetBottom.sizePolicy().hasHeightForWidth())
        self.subsetBottom.setSizePolicy(sizePolicy)
        self.subsetBottom.setObjectName(_fromUtf8('subsetBottom'))
        self.horizontalLayout_6.addWidget(self.subsetBottom)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8('label_5'))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.subsetTop = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subsetTop.sizePolicy().hasHeightForWidth())
        self.subsetTop.setSizePolicy(sizePolicy)
        self.subsetTop.setObjectName(_fromUtf8('subsetTop'))
        self.horizontalLayout_6.addWidget(self.subsetTop)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8('line_2'))
        self.verticalLayout_5.addWidget(self.line_2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8('horizontalLayout_16'))
        self.SplitByRoll = QtWidgets.QCheckBox(self.groupBox_2)
        self.SplitByRoll.setChecked(True)
        self.SplitByRoll.setObjectName(_fromUtf8('SplitByRoll'))
        self.horizontalLayout_16.addWidget(self.SplitByRoll)
        self.splitByRollAmount = QtWidgets.QSpinBox(self.groupBox_2)
        self.splitByRollAmount.setMinimum(1)
        self.splitByRollAmount.setMaximum(999999)
        self.splitByRollAmount.setObjectName(_fromUtf8('splitByRollAmount'))
        self.horizontalLayout_16.addWidget(self.splitByRollAmount)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8('line_3'))
        self.verticalLayout_5.addWidget(self.line_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8('horizontalLayout_5'))
        self.copyUseField = QtWidgets.QCheckBox(self.groupBox_2)
        self.copyUseField.setObjectName(_fromUtf8('copyUseField'))
        self.horizontalLayout_5.addWidget(self.copyUseField)
        self.copyField = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyField.sizePolicy().hasHeightForWidth())
        self.copyField.setSizePolicy(sizePolicy)
        self.copyField.setObjectName(_fromUtf8('copyField'))
        self.horizontalLayout_5.addWidget(self.copyField)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8('horizontalLayout_11'))
        self.genSamples = QtWidgets.QCheckBox(self.groupBox_2)
        self.genSamples.setObjectName(_fromUtf8('genSamples'))
        self.horizontalLayout_11.addWidget(self.genSamples)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8('label_6'))
        self.horizontalLayout_11.addWidget(self.label_6)
        self.sampleCount = QtWidgets.QSpinBox(self.groupBox_2)
        self.sampleCount.setMinimum(1)
        self.sampleCount.setMaximum(99999999)
        self.sampleCount.setObjectName(_fromUtf8('sampleCount'))
        self.horizontalLayout_11.addWidget(self.sampleCount)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8('verticalLayout_11'))
        self.individualPdfs = QtWidgets.QCheckBox(self.groupBox_2)
        self.individualPdfs.setObjectName(_fromUtf8('individualPdfs'))
        self.verticalLayout_11.addWidget(self.individualPdfs)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8('horizontalLayout_15'))
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8('label_2'))
        self.horizontalLayout_15.addWidget(self.label_2)
        self.pdfNameFormat = QtWidgets.QLineEdit(self.groupBox_2)
        self.pdfNameFormat.setObjectName(_fromUtf8('pdfNameFormat'))
        self.horizontalLayout_15.addWidget(self.pdfNameFormat)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.verticalLayout_5.addLayout(self.verticalLayout_11)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout_4.addWidget(self.frame)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8('horizontalLayout_9'))
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8('splitter_2'))
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8('layoutWidget'))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
##        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8('verticalLayout_3'))
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8('gridLayout'))
        self.headersCheck = QtWidgets.QCheckBox(self.layoutWidget)
        self.headersCheck.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.headersCheck.setObjectName(_fromUtf8('headersCheck'))
        self.gridLayout.addWidget(self.headersCheck, 11, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8('horizontalLayout_12'))
        self.previewCheck = QtWidgets.QCheckBox(self.layoutWidget)
        self.previewCheck.setObjectName(_fromUtf8('previewCheck'))
        self.horizontalLayout_12.addWidget(self.previewCheck)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8('label_7'))
        self.horizontalLayout_12.addWidget(self.label_7)
        self.previewRecord = QtWidgets.QSpinBox(self.layoutWidget)
        self.previewRecord.setObjectName(_fromUtf8('previewRecord'))
        self.horizontalLayout_12.addWidget(self.previewRecord)
        self.gridLayout.addLayout(self.horizontalLayout_12, 16, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8('horizontalLayout'))
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8('label'))
        self.horizontalLayout.addWidget(self.label)
        self.zoomLevel = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.zoomLevel.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.zoomLevel.setMinimum(10.0)
        self.zoomLevel.setMaximum(1600.0)
        self.zoomLevel.setSingleStep(5.0)
        self.zoomLevel.setProperty('value', 100.0)
        self.zoomLevel.setObjectName(_fromUtf8('zoomLevel'))
        self.horizontalLayout.addWidget(self.zoomLevel)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.createCartonLabels = QtWidgets.QPushButton(self.layoutWidget)
        self.createCartonLabels.setObjectName(_fromUtf8('createCartonLabels'))
        self.gridLayout.addWidget(self.createCartonLabels, 1, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8('horizontalLayout_14'))
        self.loadData = QtWidgets.QPushButton(self.layoutWidget)
        self.loadData.setObjectName(_fromUtf8('loadData'))
        self.horizontalLayout_14.addWidget(self.loadData)
        self.clearData = QtWidgets.QPushButton(self.layoutWidget)
        self.clearData.setObjectName(_fromUtf8('clearData'))
        self.horizontalLayout_14.addWidget(self.clearData)
        self.gridLayout.addLayout(self.horizontalLayout_14, 3, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8('horizontalLayout_2'))
        self.permitCheck = QtWidgets.QCheckBox(self.layoutWidget)
        self.permitCheck.setObjectName(_fromUtf8('permitCheck'))
        self.horizontalLayout_2.addWidget(self.permitCheck)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8('label_3'))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.permitEntry = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.permitEntry.sizePolicy().hasHeightForWidth())
        self.permitEntry.setSizePolicy(sizePolicy)
        self.permitEntry.setMaxLength(7)
        self.permitEntry.setObjectName(_fromUtf8('permitEntry'))
        self.horizontalLayout_2.addWidget(self.permitEntry)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8('horizontalLayout_3'))
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        
        # Add "100% Recyclable Packaging" textbox.
        self.recyclablePackagingCheck = QtWidgets.QCheckBox("100% Recyclable Packaging in Soft Plastics", parent=self.layoutWidget)
        self.verticalLayout_3.addWidget(self.recyclablePackagingCheck)
        self.recyclablePackagingCheck.setCheckState(Qt.Checked)
        
        self.returnCheck = QtWidgets.QCheckBox(self.layoutWidget)
        self.returnCheck.setObjectName(_fromUtf8('returnCheck'))
        self.verticalLayout_3.addWidget(self.returnCheck)
        self.returnAddress = QtWidgets.QTextEdit(self.layoutWidget)
        self.returnAddress.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.returnAddress.sizePolicy().hasHeightForWidth())
        self.returnAddress.setSizePolicy(sizePolicy)
        self.returnAddress.setMinimumSize(QtCore.QSize(0, 75))
        self.returnAddress.setMaximumSize(QtCore.QSize(16777215, 75))
        self.returnAddress.setObjectName(_fromUtf8('returnAddress'))
        self.verticalLayout_3.addWidget(self.returnAddress)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setObjectName(_fromUtf8('groupBox'))
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8('gridLayout_2'))
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 4, 0, 1, 1)
        self.addText = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addText.sizePolicy().hasHeightForWidth())
        self.addText.setSizePolicy(sizePolicy)
        self.addText.setMinimumSize(QtCore.QSize(100, 0))
        self.addText.setCheckable(True)
        self.addText.setObjectName(_fromUtf8('addText'))
        self.gridLayout_2.addWidget(self.addText, 0, 0, 1, 1)
        self.addBarcode = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addBarcode.sizePolicy().hasHeightForWidth())
        self.addBarcode.setSizePolicy(sizePolicy)
        self.addBarcode.setMinimumSize(QtCore.QSize(100, 0))
        self.addBarcode.setCheckable(True)
        self.addBarcode.setObjectName(_fromUtf8('addBarcode'))
        self.gridLayout_2.addWidget(self.addBarcode, 1, 0, 1, 1)
        self.addImage = QtWidgets.QPushButton(self.groupBox)
        self.addImage.setCheckable(True)
        self.addImage.setObjectName(_fromUtf8('addImage'))
        self.gridLayout_2.addWidget(self.addImage, 2, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.graphicsView = ZoomGraphicsView(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 290))
        self.graphicsView.viewport().setProperty('cursor', QtWidgets.QCursor(QtCore.Qt.ArrowCursor))
        self.graphicsView.setObjectName(_fromUtf8('graphicsView'))
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget.setObjectName(_fromUtf8('verticalLayoutWidget'))
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8('verticalLayout_7'))
        self.splitter = QtWidgets.QSplitter(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8('splitter'))
        self.itemList = QtWidgets.QTreeWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.itemList.sizePolicy().hasHeightForWidth())
        self.itemList.setSizePolicy(sizePolicy)
        self.itemList.setBaseSize(QtCore.QSize(0, 100))
        self.itemList.setObjectName(_fromUtf8('itemList'))
        self.itemList.headerItem().setText(0, _fromUtf8('Layout Items'))
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(350, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 500))
        self.tabWidget.setObjectName(_fromUtf8('tabWidget'))
        self.detailsTab = QtWidgets.QWidget()
        self.detailsTab.setObjectName(_fromUtf8('detailsTab'))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.detailsTab)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8('verticalLayout'))
        self.objectPropertyArea = QtWidgets.QScrollArea(self.detailsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objectPropertyArea.sizePolicy().hasHeightForWidth())
        self.objectPropertyArea.setSizePolicy(sizePolicy)
        self.objectPropertyArea.setWidgetResizable(True)
        self.objectPropertyArea.setObjectName(_fromUtf8('objectPropertyArea'))
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 342, 242))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8('scrollAreaWidgetContents'))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8('verticalLayout_2'))
        self.objectProperties = QtWidgets.QFormLayout()
        self.objectProperties.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.objectProperties.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.objectProperties.setObjectName(_fromUtf8('objectProperties'))
        self.verticalLayout_2.addLayout(self.objectProperties)
        self.objectPropertyArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.objectPropertyArea)
        self.tabWidget.addTab(self.detailsTab, _fromUtf8(''))
        self.verticalLayout_7.addWidget(self.splitter)
        self.horizontalLayout_9.addWidget(self.splitter_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8('verticalLayout_9'))
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8('label_8'))
        self.verticalLayout_9.addWidget(self.label_8)
        self.logConsole = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logConsole.sizePolicy().hasHeightForWidth())
        self.logConsole.setSizePolicy(sizePolicy)
        self.logConsole.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.logConsole.setReadOnly(True)
        self.logConsole.setObjectName(_fromUtf8('logConsole'))
        self.verticalLayout_9.addWidget(self.logConsole)
        self.verticalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_4.setStretch(1, 2)
        self.verticalLayout_4.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1218, 21))
        self.menubar.setObjectName(_fromUtf8('menubar'))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8('statusbar'))
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
        

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle('MainWindow')
        self.groupBox_4.setTitle('Headers')
        self.groupBox_3.setTitle('Layouts')
        self.filterLabel.setText('Filter')
        self.dateSort.setText('Sort by date')
        self.loadLayout.setText('Load Layout')
        self.saveLayout.setText('Save Layout')
        self.renameLayout.setText('Rename Layout')
        self.refreshLayoutList.setText('Refresh List')
        self.removeLayout.setText('Remove Layout')
        self.clearFilter.setText('Clear Filter')
        self.groupBox_2.setTitle('Print Options')
        self.createPdfBtn.setText('Create PDF')
        self.printButton.setText('Print')
        self.pageSetup.setText('Page Setup')
        self.averyRadio.setText('Avery')
        self.zebraRadio.setText('Zebra')
        self.useSubset.setText('Subset')
        self.label_4.setText('From')
        self.label_5.setText('To')
        self.SplitByRoll.setText('Split By Amount:')
        self.copyUseField.setText('Use Field for Copies')
        self.genSamples.setText('Generate Samples')
        self.label_6.setText('Amount:')
        self.individualPdfs.setText('Individual PDFs?')
        self.label_2.setToolTip('<html><head/><body><p>Same convention as label variables.</p><p>    e.g.&quot;Staff_{Name}_{Seq}.pdf&quot;</p></body></html>')
        self.label_2.setText('Naming Format')
        self.headersCheck.setText('Has Headers?')
        self.previewCheck.setText('Show Preview')
        self.label_7.setText('Record:')
        self.label.setText('Zoom:')
        self.createCartonLabels.setText('Create Carton Labels')
        self.loadData.setText('Load Data')
        self.clearData.setText('Clear Data')
        self.permitCheck.setText('Add Permit')
        self.label_3.setText('Permit No.')
        self.returnCheck.setText('Add Return Address?')
        self.groupBox.setTitle('Layup Items')
        self.addText.setText('Add Text')
        self.addBarcode.setText('Add Barcode')
        self.addImage.setText('Add Image')
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.detailsTab), 'Object Details')
        self.label_8.setText('Log Console')
        return


from zoomgraphicsview import ZoomGraphicsView

if __name__ == '__main__':
    print("asd")
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
##    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
# okay decompiling LabelDesigner.pyc
